title: APCSP PROJECT
author: Christine Chang
email: cchang2@ebnet.org
description: what am I doing

# social links
twitter_username: inumakitogesimp
github_username:  poopoopeepeepogchamp

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
