title: APCSP
author: Christine Chang
email: cchang2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  this is so difficult

# social links
twitter_username: inumakitogesimp # DO NOT include the @ character, or else the build will fail!
github_username:  poopoopeepeepogchamp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
